// src/components/investigation/InvestigationPlan.tsx

import React, { useState, useEffect } from 'react';
import { Formik, Form, Field, ErrorMessage } from 'formik';
import * as Yup from 'yup';
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { useCurrentUser } from '@/lib/hooks/useCurrentUser';
import { useCompany } from '@/lib/hooks';
import { saveInvestigationPlan } from '@/lib/services/investigationService';

// Esquema de validación para el plan de investigación
const PlanSchema = Yup.object().shape({
  description: Yup.string()
    .min(50, 'La descripción debe tener al menos 50 caracteres')
    .required('La descripción es obligatoria'),
  approach: Yup.string()
    .min(50, 'El enfoque metodológico debe tener al menos 50 caracteres')
    .required('El enfoque metodológico es obligatorio'),
  timeline: Yup.string()
    .min(50, 'El cronograma debe tener al menos 50 caracteres')
    .required('El cronograma es obligatorio'),
  specialConsiderations: Yup.string(),
});

interface InvestigationPlanProps {
  reportId: string;
  plan: any;
  reportData: any; // Datos completos de la denuncia
  isKarinLaw: boolean;
  canEdit: boolean;
  onPlanUpdated: (plan: any) => void;
}

export const InvestigationPlan: React.FC<InvestigationPlanProps> = ({
  reportId,
  plan,
  reportData,
  isKarinLaw,
  canEdit,
  onPlanUpdated,
}) => {
  const { uid, profile } = useCurrentUser();
  const { companyId: contextCompanyId } = useCompany();
  const userCompanyId = profile?.company || contextCompanyId;
  const [isEditing, setIsEditing] = useState(!(plan && typeof plan === 'object'));
  const [error, setError] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [autoGenerated, setAutoGenerated] = useState(false);
  
  // Función para generar automáticamente el plan de investigación
  const generateInvestigationPlan = () => {
    if (!reportData || typeof reportData !== 'object') return null;
    
    // Determinar el tipo de caso
    const caseType = isKarinLaw ? 'Ley Karin (acoso laboral/sexual)' : 
                    reportData.category === 'modelo_prevencion' ? 'relacionado con el Modelo de Prevención de Delitos' :
                    reportData.category === 'ciberseguridad' ? 'relacionado con Ciberseguridad' :
                    reportData.category === 'reglamento_interno' ? 'por infracciones al Reglamento Interno' :
                    reportData.category === 'politicas_codigos' ? 'relacionado con Políticas y Códigos' :
                    reportData.category === 'represalias' ? 'por posibles Represalias' : 'general';
    
    // Generar descripción automática
    const description = `
PLAN DE INVESTIGACIÓN: Denuncia #${reportData.code}

Esta denuncia ${caseType} fue recibida el ${new Date(reportData.createdAt).toLocaleDateString('es-CL')} y requiere una investigación exhaustiva y objetiva.

Descripción general del caso:
${reportData.detailedDescription || 'No se proporcionó una descripción detallada.'} 

Partes involucradas:
- Denunciante: ${reportData.anonymous ? 'Anónimo' : reportData.reporter?.contactInfo?.name || 'No especificado'}
- Denunciado(s): ${reportData.accused && reportData.accused.length > 0 ? 
  reportData.accused.map((a: any) => `${a.name || 'No especificado'} (${a.position || 'Sin posición especificada'})`).join(', ') : 
  'No especificado claramente'}
- Testigos potenciales: ${reportData.witnesses && reportData.witnesses.length > 0 ? 
  reportData.witnesses.length + ' identificados inicialmente' : 
  'No se han identificado testigos inicialmente'}

Objetivos de la investigación:
1. Determinar los hechos relevantes relacionados con la denuncia
2. Evaluar la veracidad de las alegaciones
3. Determinar si ha habido infracciones a políticas internas o normas aplicables
4. Recomendar acciones correctivas si corresponde
5. Documentar meticulosamente todo el proceso investigativo
    `;
    
    // Generar enfoque metodológico automático
    const approach = isKarinLaw ? `
ENFOQUE METODOLÓGICO LEY KARIN

Esta investigación seguirá un enfoque estructurado conforme a los requerimientos de la Ley Karin (20.607 y 21.153), garantizando confidencialidad, objetividad y respeto por los derechos de todas las partes involucradas.

Metodología a implementar:
1. Revisión documental
   - Análisis detallado de la denuncia y documentación inicial
   - Recopilación de normativa aplicable (RIOHS, políticas internas, etc.)
   - Revisión de antecedentes laborales relevantes

2. Entrevistas estructuradas
   - Entrevista al denunciante para clarificar aspectos de la denuncia
   - Entrevista(s) al denunciado(s) para obtener su versión de los hechos
   - Entrevistas a testigos identificados (directo e indirectos)
   - Entrevistas a supervisores y otros miembros relevantes del equipo

3. Recolección y análisis de evidencias
   - Comunicaciones digitales relevantes (correos, mensajes)
   - Registros de acceso o videovigilancia si fuera pertinente
   - Documentación interna relacionada con los hechos denunciados

4. Análisis y ponderación de pruebas
   - Evaluación de consistencia entre testimonios y evidencias
   - Análisis de credibilidad de testigos y versiones
   - Comparación con casos precedentes si los hubiera

5. Medidas de protección
   - Implementación y seguimiento de medidas de resguardo
   - Evaluación periódica de efectividad de las medidas
   - Ajustes según necesidad durante el proceso
    ` : `
ENFOQUE METODOLÓGICO

Esta investigación seguirá un enfoque sistemático y objetivo, garantizando un proceso justo y transparente para todas las partes involucradas.

Metodología a implementar:
1. Revisión documental
   - Análisis detallado de la denuncia y documentación inicial
   - Recopilación de normativa aplicable (políticas, procedimientos, etc.)
   - Revisión de documentación relacionada con el caso

2. Entrevistas
   - Entrevista al denunciante para obtener más detalles
   - Entrevista(s) al denunciado(s) para conocer su perspectiva
   - Entrevistas a testigos directos e indirectos
   - Entrevistas a supervisores o colegas relevantes

3. Recolección y análisis de evidencias
   - Documentos o registros relevantes
   - Comunicaciones electrónicas relacionadas
   - Otras evidencias físicas o digitales

4. Análisis
   - Evaluación de consistencia y credibilidad
   - Ponderación de testimonios y evidencias
   - Determinación de hechos probados
    `;
    
    // Generar cronograma basado en tipo de caso
    const timeline = isKarinLaw ? `
CRONOGRAMA DE INVESTIGACIÓN (CASO LEY KARIN)

Según lo establecido en la Ley Karin, esta investigación debe completarse con suma prioridad, teniendo en cuenta los siguientes plazos máximos:

Semana 1 (Inmediato - Día 3):
- Día 1: Envío de informe preliminar a la Dirección del Trabajo
- Día 1-2: Implementación de medidas de resguardo
- Día 2-3: Entrevista inicial con denunciante
- Día 3: Notificación formal al denunciado

Semana 1-2 (Día 4 - Día 10):
- Día 4-5: Entrevista con denunciado
- Día 5-7: Entrevistas con testigos identificados
- Día 7-8: Recopilación y análisis de evidencias
- Día 8-9: Análisis preliminar y hallazgos iniciales
- Día 9-10: Elaboración y presentación de informe interno de hallazgos

Consideraciones: Este cronograma podrá ajustarse según la complejidad del caso y la disponibilidad de los involucrados, pero siempre respetando los plazos legales establecidos.
    ` : `
CRONOGRAMA DE INVESTIGACIÓN

Esta investigación se desarrollará de acuerdo al siguiente cronograma tentativo:

Semana 1:
- Días 1-2: Revisión de denuncia, documentación y planificación
- Días 3-5: Entrevistas iniciales con denunciante y recopilación de evidencias iniciales
- Día 5: Evaluación preliminar y ajuste del plan si es necesario

Semana 2:
- Días 6-7: Entrevistas con denunciado(s)
- Días 8-10: Entrevistas con testigos y partes relacionadas
- Días 10-12: Análisis de evidencias y testimonios

Semana 3:
- Días 13-14: Evaluación de hallazgos preliminares
- Días 15-17: Entrevistas complementarias (si son necesarias)
- Días 17-19: Elaboración de informe de hallazgos

Semana 4:
- Días 20-22: Elaboración de informe final y recomendaciones
- Día 23: Presentación de conclusiones

Nota: Este cronograma es flexible y podrá ajustarse según la complejidad del caso y la disponibilidad de los involucrados.
    `;
    
    // Generar consideraciones especiales
    const specialConsiderations = isKarinLaw ? `
CONSIDERACIONES ESPECIALES - CASO LEY KARIN

1. Confidencialidad reforzada: Dada la naturaleza sensible de los casos de acoso, se implementarán protocolos especiales de confidencialidad, limitando el acceso a la información únicamente a las personas estrictamente necesarias.

2. Protección contra represalias: Se establecerán medidas específicas para prevenir y detectar cualquier forma de represalia contra el denunciante, testigos o participantes en la investigación.

3. Atención psicológica: Se evaluará la necesidad de proporcionar apoyo psicológico tanto al denunciante como al denunciado durante el proceso investigativo.

4. Coordinación con autoridades: Esta investigación podría requerir coordinación con la Dirección del Trabajo y otras autoridades competentes en caso de ser necesario.

5. Seguimiento post-investigación: Independientemente del resultado, se implementará un plan de seguimiento para verificar la efectividad de las medidas adoptadas y prevenir futuros incidentes.
    ` : `
CONSIDERACIONES ESPECIALES

1. Confidencialidad: Se mantendrá estricta confidencialidad durante todo el proceso investigativo para proteger la integridad de todas las partes involucradas.

2. Comunicación: Se establecerán canales apropiados para mantener informadas a las partes sobre el avance general del proceso, respetando la confidencialidad.

3. Imparcialidad: Se garantizará un enfoque imparcial en cada etapa de la investigación, evitando juicios prematuros o sesgos.

4. Documentación: Se mantendrá un registro detallado de todas las acciones realizadas durante la investigación.

5. Ajustes al plan: Este plan podrá modificarse según surjan nuevos elementos durante la investigación que requieran atención específica.
    `;
    
    return {
      description: description.trim(),
      approach: approach.trim(),
      timeline: timeline.trim(),
      specialConsiderations: specialConsiderations.trim(),
    };
  };
  
  // Generar plan automático
  const generatedPlan = generateInvestigationPlan();
  
  // Verificar si hay un plan existente y si es un objeto válido
  const hasPlan = plan && typeof plan === 'object';
  
  // Preparar valores iniciales
  const initialValues = hasPlan ? {
    description: plan.description || '',
    approach: plan.approach || '',
    timeline: plan.timeline || '',
    specialConsiderations: plan.specialConsiderations || '',
  } : generatedPlan || {
    description: '',
    approach: '',
    timeline: '',
    specialConsiderations: '',
  };
  
  // Efecto para marcar el plan como autogenerado
  useEffect(() => {
    if (!hasPlan && !autoGenerated && generatedPlan) {
      setAutoGenerated(true);
    }
  }, [hasPlan, autoGenerated, generatedPlan]);
  
  // Manejar el envío del formulario
  const handleSubmit = async (values: any) => {
    if (!uid) return;
    
    setIsSubmitting(true);
    setError(null);
    
    try {
      const result = await saveInvestigationPlan(
        userCompanyId,
        reportId,
        uid,
        values
      );
      
      if (result.success) {
        // Actualizar el plan local
        const updatedPlan = {
          ...values,
          type: 'plan',
          createdBy: uid,
          createdAt: new Date(),
          updatedAt: new Date(),
        };
        
        onPlanUpdated(updatedPlan);
        setIsEditing(false);
      } else {
        setError(result.error || 'Error al guardar el plan de investigación');
      }
    } catch (error) {
      console.error('Error al guardar el plan:', error);
      setError('Ha ocurrido un error al guardar el plan de investigación');
    } finally {
      setIsSubmitting(false);
    }
  };
  
  // Formatear fechas
  const formatDate = (date: any) => {
    if (!date) return 'N/A';
    
    const dateObj = date.toDate ? new Date(date.toDate()) : new Date(date);
    
    return new Intl.DateTimeFormat('es-CL', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    }).format(dateObj);
  };
  
  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>Plan de Investigación</CardTitle>
          <CardDescription>
            {plan 
              ? `Plan creado el ${formatDate(plan.createdAt)}` 
              : 'Defina el enfoque y los pasos a seguir en esta investigación'
            }
          </CardDescription>
        </CardHeader>
        <CardContent>
          {isKarinLaw && (
            <Alert className="mb-6 bg-red-50 border-red-200">
              <AlertDescription>
                <p className="text-red-800 font-medium">Caso Ley Karin</p>
                <p className="text-sm text-red-700 mt-1">
                  Recuerde que según la Ley Karin, la investigación debe iniciarse de inmediato una vez que se
                  valida la denuncia (cuando cumple con los antecedentes requeridos o cuando estos se subsanan dentro de los 
                  5 días hábiles posteriores). El informe preliminar debe entregarse en un plazo máximo de 3 días 
                  hábiles administrativos (sin contar sábados, domingos ni festivos) para su envío a la Dirección del Trabajo.
                </p>
              </AlertDescription>
            </Alert>
          )}
          
          {autoGenerated && !hasPlan && (
            <Alert className="mb-6 bg-yellow-50 border-yellow-200">
              <AlertDescription>
                <p className="text-yellow-800">
                  <span className="font-medium">Plan autogenerado:</span> Se ha creado automáticamente un plan de investigación 
                  basado en los datos de la denuncia. Revise y modifique la información según sea necesario antes de guardar.
                </p>
              </AlertDescription>
            </Alert>
          )}
          
          {isEditing ? (
            <Formik
              initialValues={initialValues}
              validationSchema={PlanSchema}
              onSubmit={handleSubmit}
            >
              {({ errors, touched, setFieldValue, values }) => (
                <Form className="space-y-4">
                  {/* Herramientas de ayuda para investigadores */}
                  <div className="p-4 bg-gray-50 rounded-md border border-gray-200 mb-4">
                    <h3 className="text-sm font-medium mb-2">Herramientas para generar el plan</h3>
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-2">
                      <Button 
                        type="button" 
                        variant="outline"
                        size="sm"
                        onClick={() => {
                          // Usar datos generados automáticamente
                          const generatedData = generateInvestigationPlan();
                          if (generatedData) {
                            setFieldValue('description', generatedData.description);
                            setFieldValue('approach', generatedData.approach);
                            setFieldValue('timeline', generatedData.timeline);
                            setFieldValue('specialConsiderations', generatedData.specialConsiderations);
                          }
                        }}
                      >
                        Generar Plan Automático
                      </Button>
                      
                      {/* Plantillas para diferentes casos */}
                      <div className="relative">
                        <Button 
                          type="button" 
                          variant="outline"
                          size="sm"
                          className="w-full"
                          onClick={(e) => {
                            // Mostrar/ocultar menú de enfoque metodológico
                            const target = e.currentTarget;
                            const menu = target.nextElementSibling as HTMLElement;
                            if (menu) {
                              menu.style.display = menu.style.display === 'none' ? 'block' : 'none';
                            }
                          }}
                        >
                          Plantillas de Enfoque
                        </Button>
                        <div className="absolute z-10 mt-1 w-full bg-white shadow-lg rounded-md border border-gray-200 hidden">
                          <div className="py-1">
                            <button
                              type="button"
                              className="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                              onClick={() => {
                                setFieldValue('approach', `ENFOQUE METODOLÓGICO POR TRIANGULACIÓN

Esta investigación empleará el método de triangulación, que implica recopilar y analizar datos desde diferentes perspectivas para aumentar la credibilidad y validez de los hallazgos.

1. Triangulación de datos
   - Recopilación de información de múltiples fuentes
   - Cruce de testimonios de diferentes testigos
   - Comparación de documentación con testimonios orales

2. Triangulación metodológica
   - Entrevistas individuales estructuradas y semiestructuradas
   - Análisis documental detallado
   - Observación directa cuando sea posible

3. Triangulación de investigadores
   - Participación de dos investigadores cuando sea posible
   - Revisión cruzada de hallazgos y conclusiones
   - Evaluación independiente de la evidencia clave

4. Verificación de consistencia
   - Análisis de coherencia interna de testimonios
   - Confirmación de hechos por múltiples fuentes independientes
   - Evaluación de credibilidad basada en evidencia corroborante

Este enfoque garantiza que las conclusiones estén respaldadas por evidencia sólida desde múltiples ángulos, reduciendo el riesgo de sesgos o conclusiones erróneas.`);
                              }}
                            >
                              Enfoque por Triangulación
                            </button>
                            <button
                              type="button"
                              className="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                              onClick={() => {
                                setFieldValue('approach', `ENFOQUE METODOLÓGICO BASADO EN EVIDENCIA

Esta investigación seguirá un enfoque estrictamente basado en evidencia, que prioriza hechos verificables sobre opiniones o conjeturas.

1. Jerarquía de evidencia
   - Evidencia documental contemporánea (máxima prioridad)
   - Registros y grabaciones verificables
   - Testimonios directos con detalles específicos
   - Testimonios indirectos (menor prioridad)

2. Cadena de custodia
   - Documentación rigurosa de toda evidencia recopilada
   - Registro de origen, fecha y método de obtención
   - Preservación de integridad de documentos y registros

3. Protocolos de entrevista
   - Entrevistas grabadas cuando sea posible y apropiado
   - Preguntas abiertas y no sugestivas
   - Solicitud de detalles específicos para evaluar credibilidad
   - Seguimiento sistemático para aclarar inconsistencias

4. Análisis estructurado
   - Evaluación de cada pieza de evidencia según criterios predefinidos
   - Documentación de fortalezas y limitaciones de cada evidencia
   - Construcción de conclusiones basadas en conjunto de evidencia disponible

Este enfoque asegura que las conclusiones de la investigación estén firmemente ancladas en hechos verificables, reduciendo el impacto de sesgos o percepciones subjetivas.`);
                              }}
                            >
                              Enfoque Basado en Evidencia
                            </button>
                            <button
                              type="button"
                              className="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                              onClick={() => {
                                setFieldValue('approach', isKarinLaw ? `ENFOQUE METODOLÓGICO PARA CASOS LEY KARIN

Esta investigación seguirá un enfoque especializado conforme a la Ley Karin, centrado en la protección de la dignidad y garantizando un proceso justo para todos los involucrados.

1. Entrevistas con enfoque en derechos
   - Protocolo especial para entrevistas con denunciantes de acoso
   - Técnicas de entrevista no revictimizantes
   - Preguntas enfocadas en conductas concretas, no en interpretaciones
   - Documentación detallada con consentimiento informado

2. Protección reforzada
   - Análisis de riesgos inicial para determinar medidas preventivas
   - Seguimiento continuo del bienestar del denunciante
   - Medidas de separación física y funcional cuando sea necesario
   - Confidencialidad estricta con acceso limitado a la información

3. Análisis contextual ampliado
   - Evaluación del entorno laboral y cultural
   - Análisis de relaciones de poder y posibles conflictos previos
   - Revisión de políticas internas sobre acoso y su implementación
   - Evaluación de respuestas institucionales anteriores

4. Evaluación especializada
   - Análisis sobre patrones de conducta
   - Valoración específica de impacto en la víctima
   - Evaluación de factores de riesgo para futuros incidentes
   - Determinación de acciones preventivas institucionales

Este enfoque garantiza una investigación rigurosa pero sensible, cumpliendo con los requisitos de la Ley Karin y protegiendo los derechos fundamentales de todas las partes involucradas.` : `ENFOQUE METODOLÓGICO ESTÁNDAR

Esta investigación seguirá un enfoque metódico y sistemático que asegure objetividad y exhaustividad en la evaluación del caso.

1. Etapa inicial
   - Revisión detallada de la denuncia original
   - Identificación de hechos clave y declaraciones específicas
   - Desarrollo de cronología preliminar de eventos
   - Mapeo de personas involucradas y relaciones relevantes

2. Investigación de campo
   - Entrevistas individuales con denunciante, denunciado y testigos
   - Recopilación sistemática de documentación relevante
   - Visitas al lugar de los hechos cuando corresponda
   - Obtención de registros electrónicos pertinentes

3. Análisis y verificación
   - Corroboración cruzada de testimonios
   - Validación de documentos y evidencias físicas
   - Evaluación de coherencia entre distintas fuentes
   - Identificación de discrepancias y posibles explicaciones

4. Conclusión y recomendaciones
   - Síntesis de hallazgos principales
   - Determinación de hechos probados vs. no probados
   - Análisis de infracciones a normativas aplicables
   - Desarrollo de recomendaciones apropiadas y proporcionales

Este enfoque garantiza un proceso investigativo riguroso, transparente y respetuoso de los derechos de todas las partes involucradas.`);
                              }}
                            >
                              {isKarinLaw ? 'Enfoque Ley Karin' : 'Enfoque Estándar'}
                            </button>
                          </div>
                        </div>
                      </div>
                      
                      <div className="relative">
                        <Button 
                          type="button" 
                          variant="outline"
                          size="sm"
                          className="w-full"
                          onClick={(e) => {
                            // Mostrar/ocultar menú de cronogramas
                            const target = e.currentTarget;
                            const menu = target.nextElementSibling as HTMLElement;
                            if (menu) {
                              menu.style.display = menu.style.display === 'none' ? 'block' : 'none';
                            }
                          }}
                        >
                          Plantillas de Cronograma
                        </Button>
                        <div className="absolute z-10 mt-1 w-full bg-white shadow-lg rounded-md border border-gray-200 hidden">
                          <div className="py-1">
                            <button
                              type="button"
                              className="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                              onClick={() => {
                                setFieldValue('timeline', isKarinLaw ? 
                                  generateInvestigationPlan()?.timeline || '' : 
                                  `CRONOGRAMA DE INVESTIGACIÓN ACELERADO

Esta investigación seguirá un cronograma acelerado de 2 semanas debido a la urgencia del caso:

Semana 1:
- Días 1-2: Revisión de denuncia y planificación inicial
- Día 3: Entrevista con denunciante
- Día 4: Entrevista con denunciado
- Día 5: Entrevistas con testigos principales

Semana 2:
- Día 8: Recopilación de evidencia documental
- Día 9: Entrevistas complementarias
- Día 10: Análisis de hallazgos
- Días 11-12: Elaboración del informe final
- Día 14: Presentación de conclusiones

Este cronograma podrá ajustarse según las complejidades que surjan durante la investigación.`);
                              }}
                            >
                              {isKarinLaw ? 'Cronograma Ley Karin' : 'Cronograma Acelerado (2 semanas)'}
                            </button>
                            <button
                              type="button"
                              className="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                              onClick={() => {
                                setFieldValue('timeline', `CRONOGRAMA DE INVESTIGACIÓN ESTÁNDAR

Esta investigación se desarrollará siguiendo el siguiente cronograma de 30 días:

Fase 1: Preparación (Días 1-5)
- Día 1: Revisión de denuncia y documentación inicial
- Día 2: Identificación de testigos y fuentes de evidencia
- Día 3: Desarrollo del plan detallado
- Días 4-5: Preparación de protocolos de entrevista

Fase 2: Recopilación (Días 6-15)
- Días 6-7: Entrevista con denunciante
- Días 8-9: Entrevista con denunciado
- Días 10-13: Entrevistas con testigos
- Días 14-15: Recopilación de evidencia documental

Fase 3: Análisis (Días 16-25)
- Días 16-18: Organización y revisión de evidencia
- Días 19-21: Análisis de consistencias e inconsistencias
- Días 22-23: Identificación de hallazgos clave
- Días 24-25: Determinación de conclusiones preliminares

Fase 4: Conclusión (Días 26-30)
- Días 26-28: Elaboración del informe
- Día 29: Revisión final y ajustes
- Día 30: Entrega del informe final

Este cronograma permite un análisis cuidadoso y sistemático del caso.`);
                              }}
                            >
                              Cronograma Estándar (30 días)
                            </button>
                            <button
                              type="button"
                              className="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                              onClick={() => {
                                setFieldValue('timeline', `CRONOGRAMA DE INVESTIGACIÓN DETALLADO

Este cronograma detalla cada paso del proceso investigativo, asignando tiempos específicos:

SEMANA 1: INICIO Y PLANIFICACIÓN
- Día 1: 
  * Análisis detallado de la denuncia
  * Identificación de temas clave a investigar
  * Evaluación inicial de riesgos

- Día 2:
  * Desarrollo del plan de investigación detallado
  * Asignación de recursos
  * Creación de listado preliminar de testigos

- Día 3:
  * Preparación de protocolos de entrevista
  * Recopilación de políticas y normativas aplicables
  * Organización de documentación inicial

SEMANA 2: RECOPILACIÓN DE INFORMACIÓN
- Días 4-5: Entrevista con denunciante
- Días 6-7: Entrevista con denunciado
- Días 8-10: Entrevistas con testigos identificados

SEMANA 3: EVIDENCIA Y ANÁLISIS PRELIMINAR
- Días 11-12: Recopilación de evidencia documental
- Días 13-14: Revisión de comunicaciones relevantes
- Día 15: Entrevistas de seguimiento según necesidad

SEMANA 4: ANÁLISIS PROFUNDO
- Días 16-17: Análisis de consistencias y contradicciones
- Días 18-19: Revisión de hechos probados y no probados
- Día 20: Desarrollo de hallazgos preliminares

SEMANA 5: FINALIZACIÓN
- Días 21-23: Elaboración del informe completo
- Día 24: Revisión de calidad del informe
- Día 25: Presentación de conclusiones y recomendaciones

Este cronograma podrá ajustarse según las necesidades específicas del caso.`);
                              }}
                            >
                              Cronograma Detallado (5 semanas)
                            </button>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                
                  {/* Descripción general */}
                  <div>
                    <Label htmlFor="description" required>
                      Descripción General del Caso
                    </Label>
                    <Field
                      as={Textarea}
                      id="description"
                      name="description"
                      rows={6}
                      placeholder="Describa el contexto general del caso y los aspectos clave a investigar..."
                      className={`mt-1 ${touched.description && errors.description ? 'border-error' : ''}`}
                    />
                    <ErrorMessage name="description">
                      {(msg) => <div className="text-error text-sm mt-1">{msg}</div>}
                    </ErrorMessage>
                  </div>
                  
                  {/* Enfoque metodológico */}
                  <div>
                    <Label htmlFor="approach" required>
                      Enfoque Metodológico
                    </Label>
                    <Field
                      as={Textarea}
                      id="approach"
                      name="approach"
                      rows={6}
                      placeholder="Detalle qué métodos de investigación utilizará, qué fuentes de información consultará, qué tipos de evidencia buscará..."
                      className={`mt-1 ${touched.approach && errors.approach ? 'border-error' : ''}`}
                    />
                    <ErrorMessage name="approach">
                      {(msg) => <div className="text-error text-sm mt-1">{msg}</div>}
                    </ErrorMessage>
                  </div>
                  
                  {/* Cronograma */}
                  <div>
                    <Label htmlFor="timeline" required>
                      Cronograma de Investigación
                    </Label>
                    <Field
                      as={Textarea}
                      id="timeline"
                      name="timeline"
                      rows={6}
                      placeholder="Establezca las etapas de la investigación con plazos específicos para cada actividad..."
                      className={`mt-1 ${touched.timeline && errors.timeline ? 'border-error' : ''}`}
                    />
                    <ErrorMessage name="timeline">
                      {(msg) => <div className="text-error text-sm mt-1">{msg}</div>}
                    </ErrorMessage>
                  </div>
                  
                  {/* Consideraciones especiales */}
                  <div>
                    <Label htmlFor="specialConsiderations">
                      Consideraciones Especiales (opcional)
                    </Label>
                    <Field
                      as={Textarea}
                      id="specialConsiderations"
                      name="specialConsiderations"
                      rows={4}
                      placeholder="Indique cualquier consideración especial, riesgos potenciales o limitaciones de la investigación..."
                      className="mt-1"
                    />
                  </div>
                  
                  {error && (
                    <Alert variant="error">
                      <AlertDescription>{error}</AlertDescription>
                    </Alert>
                  )}
                  
                  <div className="flex justify-end space-x-2 pt-4">
                    {plan && (
                      <Button
                        type="button"
                        variant="outline"
                        onClick={() => setIsEditing(false)}
                        disabled={isSubmitting}
                      >
                        Cancelar
                      </Button>
                    )}
                    <Button 
                      type="submit"
                      disabled={isSubmitting}
                    >
                      {isSubmitting ? 'Guardando...' : plan ? 'Actualizar Plan' : 'Crear Plan'}
                    </Button>
                  </div>
                </Form>
              )}
            </Formik>
          ) : (
            <div className="space-y-6">
              <div>
                <h3 className="text-sm font-medium text-gray-700 mb-2">Descripción General del Caso</h3>
                <div className="bg-gray-50 p-4 rounded-md border border-gray-200">
                  <p className="text-sm text-gray-800 whitespace-pre-line">{plan.description}</p>
                </div>
              </div>
              
              <div>
                <h3 className="text-sm font-medium text-gray-700 mb-2">Enfoque Metodológico</h3>
                <div className="bg-gray-50 p-4 rounded-md border border-gray-200">
                  <p className="text-sm text-gray-800 whitespace-pre-line">{plan.approach}</p>
                </div>
              </div>
              
              <div>
                <h3 className="text-sm font-medium text-gray-700 mb-2">Cronograma de Investigación</h3>
                <div className="bg-gray-50 p-4 rounded-md border border-gray-200">
                  <p className="text-sm text-gray-800 whitespace-pre-line">{plan.timeline}</p>
                </div>
              </div>
              
              {plan.specialConsiderations && (
                <div>
                  <h3 className="text-sm font-medium text-gray-700 mb-2">Consideraciones Especiales</h3>
                  <div className="bg-gray-50 p-4 rounded-md border border-gray-200">
                    <p className="text-sm text-gray-800 whitespace-pre-line">{plan.specialConsiderations}</p>
                  </div>
                </div>
              )}
              
              {canEdit && (
                <div className="flex justify-end">
                  <Button 
                    onClick={() => setIsEditing(true)}
                    variant="outline"
                  >
                    Editar Plan
                  </Button>
                </div>
              )}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
};